blank_issues_enabled: true
contact_links:
  - name: â“Usage Questions
    url: https://github.com/redhat-ux/red-hat-design-system/discussions/new?category=q-a
    about: Questions about how to use RHDS Components? Please ask them in Discussions

  - name: ğŸ’¡Ideas
    url: https://github.com/redhat-ux/red-hat-design-system/discussions/new?category=ideas
    about: Ideas for new components or features which aren't ready for design

  - name: Code of Conduct Violation
    url: https://mailxto.com/2xn950
    about: Please report code of conduct violations here.
